version: '2'
services:
  container:
    image: storjlabs/thor:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/thor/thor-development.dockerfile
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '../thorfiles/container.thor:/storj-base/Thorfile'
      - '../thorfiles/lib:/storj-base/thorfiles'
      - '../dockerfiles/:/storj-base/dockerfiles'
    environment:
      CONTEXT: container
  host:
    image: storjlabs/thor:latest
    build:
      context: ../
      dockerfile: ./dockerfiles/thor/thor-development.dockerfile
    privileged: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '../:/storj-base'
      - '../thorfiles/host.thor:/storj-base/Thorfile'
      - '../thorfiles/lib:/storj-base/thorfiles'
    environment:
      CONTEXT: host
